UNMAPPED_ID = -1
MIDI_MASTER_CHANNEL = 7
MIDI_TRACKS_CHANNEL = 8
MIDI_SENDS_CHANNEL = 9


MAX_NO_OF_SENDS = 5 # actually CC assignment dimensioned for 6 mostly
NO_OF_TRACKS = 6

# - On MIDI_MASTER_CHANNEL

MASTER_PAN_CC = 0
MASTER_VOLUME_CC = 1
MASTER_CUE_VOLUME_CC = 2
MASTER_SOLO_CC = 71

MASTER_DEVICE_SELECTION_CC = 96

RETURNS_PAN_CC = 8 
RETURNS_VOLUME_CC = 14
RETURNS_MUTE_CC = 78
RETURNS_SOLO_CUE_CC = 84

RM_DEVICE_SELECTION_CC = 90

PLAY_STOP_CC = 72
RECORD_CC = 73
POSITION_CC = 74
TEMPO_CC = 75

PREV_TRACKS_CC = 76
NEXT_TRACKS_CC = 77
PAGE_UP_CC = 97
PAGE_DOWN_CC = 98

MASTER_EQ_CC_MAP = { 
              'Highpass On': (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 0, 70)
            , 'Low Gain':    (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 6)
            , 'Mid Gain':    (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 5)
            , 'Mid Freq':    (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 4)
            , 'High Gain':   (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 3)
            , 'Gain':        (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 7)
            }

# - On MIDI_TRACKS_CHANNEL

PAN_CC = 0
VOLUME_CC = 6
MUTE_CC = 70
SOLO_CUE_CC = 76
ARM_CC = 82

DEVICE_SELECTION_CC = 88

TRACK_EQ_CC_MAP = { 
              'Highpass On': (UNMAPPED_ID, MIDI_TRACKS_CHANNEL, 0, 64)
            , 'Low Gain'   : (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 26)
            , 'Mid Gain'   : (UNMAPPED_ID, MIDI_TRACKS_CHANNEL, 1, 24)
            , 'Mid Freq'   : (UNMAPPED_ID, MIDI_TRACKS_CHANNEL, 1, 18)
            , 'High Gain'  : (UNMAPPED_ID, MIDI_TRACKS_CHANNEL, 1, 12)
            , 'Gain'       : (UNMAPPED_ID, MIDI_MASTER_CHANNEL, 1, 20)
            }

# - On MIDI_SENDS_CHANNEL

SENDS_CC = 0
PADS_CC = 65
SESSION_SLOT_CC = 64

