#!/usr/local/bin/python3
# 
# ElectrOne 
#
# Ableton Live MIDI Remote Script for the Electra One
#
# makedevices: a script to make Devices.py
#
# Author: Jaap-henk Hoepman (info@xot.nl)
#
# Distributed under the MIT License, see LICENSE

from pathlib import Path

PREAMBLE = """
# ElectrOne - Device definitions
#
# Ableton Live MIDI Remote Script for the Electra One
#
# Author: Jaap-henk Hoepman (info@xot.nl)
#
# Distributed under the MIT License, see LICENSE
#

# Dictionary with preset and MIDI cc mapping data for known devices
# (indexed by device.original_name)
# - The preset is a JSON string in Electra One format.
#   (The current implementation assumes that all quantized parameters
#   are 7-bit absolute CC values while all non quantized parameters are
#   14-bit absolute values)
# - The MIDI cc mapping data is a dictionary of Ableton Live original parameter
#   names with their corresponding MIDI CC values in the preset.
#

from .ElectraOneDumper import PatchInfo
"""

POSTSCRIPT = """
# Return the predefined patch information for a device, None if it doesn't exist
def get_predefined_patch_info(device_original_name):
    # FIXME: try to read from file
    if device_original_name in DEVICES:
        return DEVICES[device_original_name]
    else:
        return None
"""

# Output file
DEVICES = 'Devices.py'

here = Path('.')
allpresets = here.glob('preloaded/*.epr')
with open(DEVICES,'w') as outf:
    outf.write(PREAMBLE)
    outf.write('\nDEVICES = {\n')
    flag = False
    for preset in allpresets:
        json_patch_path = preset
        ccmap_path = preset.with_suffix('.ccmap')
        device_name = preset.stem
        if flag:
            outf.write(',\n')
        flag = True
        with open(json_patch_path,'r') as inf:
            json_patch = inf.read()
            # escape single quotes in json_patch; it will be written
            # as a single-quoted string to Devices.py
            filter_quotes = str.maketrans({ "'": "\\'"})
            json_patch = json_patch.translate(filter_quotes)
        with open(ccmap_path,'r') as inf:
            ccmap = inf.read()
            # Remove newlines from ccmap
            filter_newlines = str.maketrans({ '\n': None})
            ccmap = ccmap.translate(filter_newlines)
        outf.write(f"'{ device_name }': PatchInfo('")
        outf.write(json_patch)
        outf.write("',\n    ")
        outf.write(ccmap)
        outf.write(')')
    outf.write('\n}\n\n')
    outf.write(POSTSCRIPT)
